### ISSUE TITLE
Use github actions outputs, not `env`

### ISSUE THREAD

**Issue by thclark** [octue/generate-pull-request-description#3]
### Use Case

We want to be able to reuse the text output in subsequent jobs or reusable workflows

### Current state

Current usage instructions look like this:
```
- uses: octue/generate-pull-request-description@1.0.0.beta-0
  with:
    pull_request_url: ${{ github.event.pull_request.url }}
    api_token: ${{ secrets.GITHUB_TOKEN }}

- name: Update pull request body
  uses: riskledger/update-pr-description@v2
  with:
    body: ${{ env.PULL_REQUEST_DESCRIPTION }}
    token: ${{ secrets.GITHUB_TOKEN }}
```

What's happening is that the action is putting outputs into the github actions `env`ironment, visible to all subsequent actions but not usable in subsequent jobs. This comes from before GitHub had a way of dealing with outputs.

GitHub actions now [allows steps to run complex commands, including setting outputs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) which can then be reused in subsequent jobs (only the subsequent jobs where you want them) and reusable workflows [like this](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs).

### Suggested action

Alter the outputs to be set via command rather than attached to env, update usage instructions accordingly.
